apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: default
  flux-system: 
spec:
  selector:
    matchLabels:
      app: httpddeployment
  replicas: 1
  template:
    metadata:
      labels:
        app: httpddeployment
    spec:
      containers:
      - name: httpddeployment
        image: nginx:latest
        ports:
        - containerPort: 80